language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - sudo apt update
#  - wget https://github.com/ThunderFly-aerospace/Slic3r/releases/download/TFv0.1/Slic3r-1.3.1-dev-ebe35c30-.AppImage -O ~/Slic3r.AppImage
#  - chmod +x ~/Slic3r.AppImage
install:
  - sudo apt install -y slic3r
  - pip3 install --upgrade pip
  - pip3 install lxml
  #- pip3 install processor3D
  - pip3 install git+https://github.com/ThunderFly-aerospace/processor3D.git
  - pip3 install git+https://github.com/ThunderFly-aerospace/yagv
  - sudo snap install openscad-nightly
#  - pip3 install -r requirements.txt
script:
  -  ~/Slic3r.AppImage --no_gui
  - cd CAD; make
  - ./build.sh
