language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip3 install --upgrade pip 
  - pip3 install processor3D
#  - pip3 install -r requirements.txt
# command to run tests
script:
  - build.sh
