STL_DIR=../../stl
AMF_DIR=../../amf
IMG_DIR=img
SRC_DIR=../../src/printplate
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../../
OUTPUT_FOLDER=CAD
NAME_PREFIX=TF-G2
include ../../../utils/Makefile
