STL_DIR=../../stl
AMF_DIR=../../amf
IMG_DIR=png
# FIXED: do only assembly targets
# SRC_DIR=../../src/assembly/position
#         must be done in itself directory
# see ../../../.github/workflows/render_previews.yml
SRC_DIR=../../src/assembly
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../../
OUTPUT_FOLDER=.
NAME_PREFIX=TF-G2_assembly
PROCESSOR3D_PARAM=--no_gcode --no_amf

include ../../../utils/Makefile
