STL_DIR=../../stl
AMF_DIR=../../amf
# FIXED: do only assembly targets
# SRC_DIR=../../src/assembly/position
#         must be done in itself directory
# see ../../../.github/workflows/render_previews.yml
SRC_DIR=../../src/assembly
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../../
OUTPUT_FOLDER=CAD
# is taken from GIT_ROOT/OUTPUT_FOLDER
IMG_FOLDER=../doc/assembly_guide/img
NAME_PREFIX=TF-G2
PROCESSOR3D_PARAM=--no_gcode --no_amf --img_folder "$(IMG_FOLDER)"

include ../../../utils/Makefile
