STL_DIR=../../stl
AMF_DIR=../../amf
# IMG_DIR=../../img
SRC_DIR=../../src/assembly/position
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../../
OUTPUT_FOLDER=CADa
NAME_PREFIX=TF-G2_assembly


include ../../../utils/Makefile
