STL_DIR=../../stl
AMF_DIR=../../amf
IMG_DIR=png
SRC_DIR=../../src/assembly/position
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../../
OUTPUT_FOLDER=.
NAME_PREFIX=TF-G2_drawing
PROCESSOR3D_PARAM=--no_gcode --no_amf

include ../../../utils/Makefile
