STL_DIR=../../src/build_manual/stl
#AMF_DIR=../../amf
IMG_DIR=png
SRC_DIR=../../src/build_manual/src
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../../
# FIXME: this should be '.' and STL files should be taken from ../../stl
OUTPUT_FOLDER=./src/build_manual/
NAME_PREFIX=TF-G2_bman
# FIXME: --no_render
PROCESSOR3D_PARAM=--no_gcode --no_amf

include ../../../utils/Makefile
