STL_DIR=../stl
#AMF_DIR=../../amf
IMG_DIR=png
SRC_DIR=../src
# DEP_DIR=../../dep
# GCD_DIR=../../gcode
# INI_DIR=../../slicing
GIT_ROOT=../../
OUTPUT_FOLDER=CAD
NAME_PREFIX=TF-G2
PROCESSOR3D_PARAM=--force --no_gcode --no_amf

include ../../utils/Makefile
