STL_DIR=../../../stl
AMF_DIR=../../../amf
IMG_DIR=png
SRC_DIR=../../../src/assembly/test
# DEP_DIR=../../../dep
# GCD_DIR=../../../gcode
# INI_DIR=../../../slicing
GIT_ROOT=../../../../
# FIXME: this is due to SRC+OUTPUT is at GIT ROOT
OUTPUT_FOLDER=CAD
NAME_PREFIX=TF-G2_assembly
PROCESSOR3D_PARAM=--no_gcode --no_amf

include ../../../../utils/Makefile
