STL_DIR=../../../stl
AMF_DIR=../../../amf
SRC_DIR=../../../src/assembly/test
# DEP_DIR=../../../dep
# GCD_DIR=../../../gcode
# INI_DIR=../../../slicing
GIT_ROOT=../../../../
# FIXME: this is due to SRC+OUTPUT is at GIT ROOT
OUTPUT_FOLDER=CAD
# is taken from GIT_ROOT/OUTPUT_FOLDER
IMG_FOLDER=../doc/assembly_guide/img
NAME_PREFIX=TF-G2
PROCESSOR3D_PARAM=--no_gcode --no_amf --img_folder "$(IMG_FOLDER)"

include ../../../../utils/Makefile
