name: Build repository

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        uname -p
        sudo apt update
        wget https://dl.slic3r.org/linux/Slic3r-1.3.0-x86_64.AppImage -O ~/Slic3r.AppImage
        chmod +x ~/Slic3r.AppImage
        sudo apt-get install libc-bin=2.27-3ubuntu1 python3-setuptools
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install lxml
        # sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/processor3D.git
        sudo python3 -m pip install processor3D
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/yagv
        sudo snap install openscad-nightly
        # processor3D

    - name: Make
      run: |
        cd CAD; make
