name: Build printable files

on:
  push:
    branches:
     - master
     - 4s
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      OPENSCAD_BIN: openscad-nightly
      SLIC3R_BIN: ~/Slic3r.AppImage

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        uname -p
        sudo apt update
        wget https://dl.slic3r.org/linux/Slic3r-1.3.0-x86_64.AppImage -O ~/Slic3r.AppImage
        chmod +x ~/Slic3r.AppImage
        sudo apt-get install libc-bin python3-setuptools
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install stlsort
        sudo python3 -m pip install lxml
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/yagv
        sudo python3 -m pip install git+https://${{ secrets.AUTH_USER }}:${{ secrets.GITHUBPAT }}@github.com/ThunderFly-aerospace/processor3D.git
        sudo snap install openscad-nightly
        openscad-nightly --version

    - name: Make
      run: |
        cd CAD/src/printplate; make

    - name: Upload gcodes
      uses:  MLAB-project/push-generated-file@master
      with:
        source_file_path: 'CAD/gcode'
        destination_folder: 'gcode'
        destination_repo: 'ThunderFly-aerospace/gcodes'
        target_branch:  TF-G2/edee
        token: ${{ secrets.GITHUBPAT }}

    - name: Upload images
      uses:  MLAB-project/push-generated-file@master
      with:
        source_file_path: 'CAD/png/printplate*'
        destination_folder: 'png'
        destination_repo: 'ThunderFly-aerospace/gcodes'
        target_branch:  TF-G2/edee
        token: ${{ secrets.GITHUBPAT }}


#    - name: publish to git
#      run: |
#        git config --local user.email "work.flow@gmail.com"
#        git config --local user.name "Workflow"
#        git commit -m "Automatic commit from workflow" -a
#        git push
