name: Build repository

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        uname -p
        sudo apt update
        wget https://dl.slic3r.org/linux/Slic3r-1.3.0-x86_64.AppImage -O ~/Slic3r.AppImage
        chmod +x ~/Slic3r.AppImage
        sudo apt-get install libc-bin=2.27-3ubuntu1 python3-setuptools
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install lxml
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/processor3D.git
        #sudo python3 -m pip install processor3D
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/yagv
        # sudo python3 -m pip install yagv
        sudo snap install openscad-nightly
        alias openscad=openscad-nightly

    - name: Make
      run: |
        cd CAD/src/printplate; make

    #- name: Push
    #  uses: mikeal/publish-to-github-action@master
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GitHubToken }}

    - name: publish to git
      run: |
        git config --local user.email "work.flow@gmail.com"
        git config --local user.name "Workflow"
        git commit -m "Automatic commit from workflow" -a
        git push
