name: Render previews

on:
  push:
    branches:
     - '*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.actor != 'TFbot'}}

    env:
      OPENSCAD_BIN: xvfb-run --auto-servernum ~/OpenSCAD.AppImage

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUBPAT }}
        submodules: recursive
#     - name: Checkout submodules
#       run: git -c submodule."CAD/slicing".update=none submodule update --init --recursive
      
    - name: Install requirements
      run: |
        uname -p
        sudo apt update
        sudo apt-get install libc-bin python3-setuptools xvfb
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install stlsort
        sudo python3 -m pip install lxml
        sudo python3 -m pip install git+https://github.com/ThunderFly-aerospace/yagv
        sudo python3 -m pip install git+https://${{ secrets.AUTH_USER }}:${{ secrets.GITHUBPAT }}@github.com/ThunderFly-aerospace/processor3D.git
        wget https://files.openscad.org/OpenSCAD-2021.01-x86_64.AppImage -O ~/OpenSCAD.AppImage
        chmod +x ~/OpenSCAD.AppImage
        ~/OpenSCAD.AppImage --version

    - name: Make
      run: |
        #cd CAD/src
        #make
        echo "ahoj" > test.txt

    - name: Upload a PNG Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: 'render_png'
        path: './**/*.png'

    - name: Upload a STL Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: 'render_stl'
        path: './**/*.stl'

    - name: publish to git        
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic commit from workflow
        commit_author: 'TFbot'
